title: (the) Michael Warren
url: "https://themichaelwarren.com"
baseurl: "/mjw"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/themichaelwarren"
footer_text: "themichaelwarren.com"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/mjw/"
 - name: "Music"
   link: "/mjw/music"
 - name: "Contact"
   link: "contact"
